/*
 * $Id: ObjectFactory.java,v 1.2.2.1 2012-05-11 10:14:33 pah Exp $
 * Copyright 2011 Paul Harrison (paul.harrison@manchester.ac.uk)
 *
 * File originally generated by JAXB, but since hand updated
 */


package org.javastro.ivoa.entities.regtap;

import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.ivoa.resource package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ContentSubject_QNAME = new QName("", "subject");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.ivoa.gtap
     * 
     */
    public ObjectFactory() {
    }

   /**
     * Create an instance of {@link Date }.
     * 
     */
    public Date createDate() {
        return new Date();
    }

 
    /**
     * Create an instance of {@link Relationship }.
     * 
     */
    public Relationship createRelationship() {
        return new Relationship();
    }


    /**
     * Create an instance of {@link Capability }.
     * 
     */
    public Capability createCapability() {
        return new Capability();
    }

    /**
     * Create an instance of {@link Resource }.
     * 
     */
    public Resource createResource() {
        return new Resource();
    }
    
    public Interface createInterface(){
        return new Interface();
    }
    
    public IntfParam createIntfParam(){
        return new IntfParam();
    }

//    /**
//     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}.
//     * 
//     */
//    @XmlElementDecl(namespace = "", name = "subject", scope = Content.class)
//    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
//    public JAXBElement<String> createContentSubject(String value) {
//        return new JAXBElement<String>(_ContentSubject_QNAME, String.class, Content.class, value);
//    }

}
